import type { PalletMetadata } from '@/lib/types'

export const extrinsicsMetadata: PalletMetadata = {
  "Acurast": ["deregister", "register", "register_with_min_metrics", "set_environment", "set_environments", "submit_attestation", "update_allowed_sources", "update_certificate_revocation_list"],
  "AcurastCandidatePreselection": ["add_candidate", "remove_candidate"],
  "AcurastCompute": ["accept_backing_offer", "commit_compute", "compound_delegation", "compound_stake", "cooldown_compute_commitment", "cooldown_delegation", "create_pool", "delegate", "delegate_more", "end_compute_commitment", "end_delegation", "kick_out", "modify_pool", "offer_backing", "redelegate", "slash", "stake_more", "withdraw_backing_offer", "withdraw_commitment", "withdraw_delegation"],
  "AcurastHyperdrive": ["update_aleph_zero_contract", "update_vara_contract"],
  "AcurastHyperdriveIbc": ["clean_incoming", "confirm_message_delivery", "receive_message", "remove_message", "send_test_message", "update_oracles"],
  "AcurastHyperdriveToken": ["enable_proxy_chain", "retry_transfer_native", "set_enabled", "transfer_native", "update_ethereum_contract", "update_solana_contract"],
  "AcurastMarketplace": ["acknowledge_execution_match", "acknowledge_match", "advertise", "cleanup_assignments", "cleanup_assignments_for", "cleanup_job_assignments", "cleanup_storage", "delete_advertisement", "deploy", "edit_script", "finalize_job", "finalize_jobs", "propose_execution_matching", "propose_matching", "report", "transfer_editor", "update_min_fee_per_millisecond"],
  "AcurastProcessorManager": ["advertise_for", "heartbeat", "heartbeat_with_metrics", "heartbeat_with_version", "multi_pair_with_manager", "onboard", "pair_with_manager", "recover_funds", "set_management_endpoint", "set_migration_data", "set_processor_update_info", "update_api_version", "update_binary_hash", "update_min_processor_version_for_reward", "update_onboarding_settings", "update_processor_pairings", "update_reward_distribution_settings"],
  "AcurastTokenClaim": ["claim", "vest"],
  "AcurastTokenConversion": ["convert", "retry_convert", "retry_convert_for", "retry_process_conversion", "retry_process_conversion_for", "set_enabled", "unlock"],
  "Balances": ["burn", "force_adjust_total_issuance", "force_set_balance", "force_transfer", "force_unreserve", "transfer_all", "transfer_allow_death", "transfer_keep_alive", "upgrade_accounts"],
  "CollatorSelection": ["add_invulnerable", "leave_intent", "register_as_candidate", "remove_invulnerable", "set_candidacy_bond", "set_desired_candidates", "set_invulnerables", "take_candidate_slot", "update_bond"],
  "ConvictionVoting": ["delegate", "remove_other_vote", "remove_vote", "undelegate", "unlock", "vote"],
  "Council": ["close", "disapprove_proposal", "execute", "kill", "propose", "release_proposal_cost", "set_members", "vote"],
  "CouncilMembership": ["add_member", "change_key", "clear_prime", "remove_member", "reset_members", "set_prime", "swap_member"],
  "ExtraFunds": ["check_status", "payout", "remove_approval", "spend", "spend_local", "void_spend"],
  "LiquidityFunds": ["check_status", "payout", "remove_approval", "spend", "spend_local", "void_spend"],
  "MessageQueue": ["execute_overweight", "reap_page"],
  "Multisig": ["approve_as_multi", "as_multi", "as_multi_threshold_1", "cancel_as_multi", "poke_deposit"],
  "OperationFunds": ["check_status", "payout", "remove_approval", "spend", "spend_local", "void_spend"],
  "ParachainSystem": ["set_validation_data", "sudo_send_upward_message"],
  "PolkadotXcm": ["add_authorized_alias", "claim_assets", "execute", "force_default_xcm_version", "force_subscribe_version_notify", "force_suspension", "force_unsubscribe_version_notify", "force_xcm_version", "limited_reserve_transfer_assets", "limited_teleport_assets", "remove_all_authorized_aliases", "remove_authorized_alias", "reserve_transfer_assets", "send", "teleport_assets", "transfer_assets", "transfer_assets_using_type_and_then"],
  "Preimage": ["ensure_updated", "note_preimage", "request_preimage", "unnote_preimage", "unrequest_preimage"],
  "Proxy": ["add_proxy", "announce", "create_pure", "kill_pure", "poke_deposit", "proxy", "proxy_announced", "reject_announcement", "remove_announcement", "remove_proxies", "remove_proxy"],
  "Referenda": ["cancel", "kill", "nudge_referendum", "one_fewer_deciding", "place_decision_deposit", "refund_decision_deposit", "refund_submission_deposit", "set_metadata", "submit"],
  "Scheduler": ["cancel", "cancel_named", "cancel_retry", "cancel_retry_named", "schedule", "schedule_after", "schedule_named", "schedule_named_after", "set_retry", "set_retry_named"],
  "Session": ["purge_keys", "set_keys"],
  "Sudo": ["remove_key", "set_key", "sudo", "sudo_as", "sudo_unchecked_weight"],
  "System": ["apply_authorized_upgrade", "authorize_upgrade", "authorize_upgrade_without_checks", "kill_prefix", "kill_storage", "remark", "remark_with_event", "set_code", "set_code_without_checks", "set_heap_pages", "set_storage"],
  "Timestamp": ["set"],
  "Treasury": ["check_status", "payout", "remove_approval", "spend", "spend_local", "void_spend"],
  "Uniques": ["approve_transfer", "burn", "buy_item", "cancel_approval", "clear_attribute", "clear_collection_metadata", "clear_metadata", "create", "destroy", "force_create", "force_item_status", "freeze", "freeze_collection", "mint", "redeposit", "set_accept_ownership", "set_attribute", "set_collection_max_supply", "set_collection_metadata", "set_metadata", "set_price", "set_team", "thaw", "thaw_collection", "transfer", "transfer_ownership"],
  "Utility": ["as_derivative", "batch", "batch_all", "dispatch_as", "dispatch_as_fallible", "force_batch", "if_else", "with_weight"],
  "Vesting": ["force_remove_vesting_schedule", "force_vested_transfer", "merge_schedules", "vest", "vest_other", "vested_transfer"],
  "XcmpQueue": ["resume_xcm_execution", "suspend_xcm_execution", "update_drop_threshold", "update_resume_threshold", "update_suspend_threshold"]
}

export const eventsMetadata: PalletMetadata = {
  "Acurast": ["AllowedSourcesUpdated", "AllowedSourcesUpdatedV2", "AttestationStored", "AttestationStoredV2", "CertificateRevocationListUpdated", "ExecutionEnvironmentsUpdated", "ExecutionEnvironmentsUpdatedV2", "JobRegistrationRemoved", "JobRegistrationStored", "JobRegistrationStoredV2", "V5MigrationCompleted", "V5MigrationProgress", "V5MigrationStarted"],
  "AcurastCandidatePreselection": ["CandidateAdded", "CandidateRemoved"],
  "AcurastCompute": ["BackingAccepted", "BackingOfferWithdrew", "BackingOffered", "CommitmentCreated", "CommitterCompounded", "CommitterWithdrew", "ComputeCommitmentCooldownStarted", "ComputeCommitmentEnded", "ComputeCommitted", "Delegated", "DelegatedMore", "DelegationCooldownStarted", "DelegationEnded", "DelegatorCompounded", "DelegatorWithdrew", "KickedOut", "PoolCreated", "Redelegated", "Slashed", "StakedMore", "V11MigrationCompleted", "V11MigrationStarted"],
  "AcurastHyperdrive": ["AlephZeroContractUpdated", "ReceivedFromProxy", "SentToProxy", "SentToProxyV2", "VaraContractUpdated"],
  "AcurastHyperdriveIbc": ["MessageDelivered", "MessageProcessed", "MessageProcessedWithErrors", "MessageReadyToSend", "MessageRemoved", "OracleUpdated"],
  "AcurastHyperdriveToken": ["EthereumContractUpdated", "PalletEnabled", "SolanaContractUpdated", "TransferFromProxy", "TransferToProxy"],
  "AcurastMarketplace": ["AdvertisementRemoved", "AdvertisementStored", "AdvertisementStoredV2", "EditorTransferred", "ExecutionFailure", "ExecutionSuccess", "JobAssignmentsCleanedUp", "JobBecameImmutable", "JobExecutionMatched", "JobExecutionMatchedV2", "JobFinalized", "JobRegistrationAssigned", "JobRegistrationAssignedV2", "JobRegistrationMatched", "JobRegistrationMatchedV2", "JobScriptEdited", "MinFeePerMillisecondUpdated", "ProcessorAssignmentsCleanedUp", "Reported", "ReportedV2", "V7MigrationCompleted", "V7MigrationStarted"],
  "AcurastProcessorManager": ["ApiVersionUpdated", "BinaryHashUpdated", "ManagerCreated", "MinProcessorVersionForRewardUpdated", "OnboardingSettingsUpdated", "ProcessorAdvertisement", "ProcessorAdvertisementV2", "ProcessorFundsRecovered", "ProcessorHeartbeat", "ProcessorHeartbeatWithVersion", "ProcessorMigrationDataSet", "ProcessorPaired", "ProcessorPairedV2", "ProcessorPairingsUpdated", "ProcessorRewardSent", "ProcessorUpdateInfoSet"],
  "AcurastRewardsTreasury": ["BurntFromTreasuryAtEndOfEpoch"],
  "AcurastTokenClaim": ["Claimed", "ClaimedV2", "Vested"],
  "AcurastTokenConversion": ["ConversionInitiated", "ConversionLockDurationUpdate", "ConversionNotProcessed", "ConversionProcessed", "ConversionRetried", "ConversionUnlocked"],
  "Balances": ["BalanceSet", "Burned", "Deposit", "DustLost", "Endowed", "Frozen", "Issued", "Locked", "Minted", "Rescinded", "ReserveRepatriated", "Reserved", "Restored", "Slashed", "Suspended", "Thawed", "TotalIssuanceForced", "Transfer", "Unlocked", "Unreserved", "Upgraded", "Withdraw"],
  "CollatorSelection": ["CandidateAdded", "CandidateBondUpdated", "CandidateRemoved", "CandidateReplaced", "InvalidInvulnerableSkipped", "InvulnerableAdded", "InvulnerableRemoved", "NewCandidacyBond", "NewDesiredCandidates", "NewInvulnerables"],
  "ConvictionVoting": ["Delegated", "Undelegated", "VoteRemoved", "VoteUnlocked", "Voted"],
  "Council": ["Approved", "Closed", "Disapproved", "Executed", "Killed", "MemberExecuted", "ProposalCostBurned", "ProposalCostReleased", "Proposed", "Voted"],
  "CouncilMembership": ["Dummy", "KeyChanged", "MemberAdded", "MemberRemoved", "MembersReset", "MembersSwapped"],
  "CumulusXcm": ["ExecutedDownward", "InvalidFormat", "UnsupportedVersion"],
  "ExtraFunds": ["AssetSpendApproved", "AssetSpendVoided", "Awarded", "Burnt", "Deposit", "Paid", "PaymentFailed", "Rollover", "SpendApproved", "SpendProcessed", "Spending", "UpdatedInactive"],
  "LiquidityFunds": ["AssetSpendApproved", "AssetSpendVoided", "Awarded", "Burnt", "Deposit", "Paid", "PaymentFailed", "Rollover", "SpendApproved", "SpendProcessed", "Spending", "UpdatedInactive"],
  "MessageQueue": ["OverweightEnqueued", "PageReaped", "Processed", "ProcessingFailed"],
  "Multisig": ["DepositPoked", "MultisigApproval", "MultisigCancelled", "MultisigExecuted", "NewMultisig"],
  "OperationFunds": ["AssetSpendApproved", "AssetSpendVoided", "Awarded", "Burnt", "Deposit", "Paid", "PaymentFailed", "Rollover", "SpendApproved", "SpendProcessed", "Spending", "UpdatedInactive"],
  "ParachainSystem": ["DownwardMessagesProcessed", "DownwardMessagesReceived", "UpwardMessageSent", "ValidationFunctionApplied", "ValidationFunctionDiscarded", "ValidationFunctionStored"],
  "PolkadotXcm": ["AliasAuthorizationRemoved", "AliasAuthorized", "AliasesAuthorizationsRemoved", "AssetsClaimed", "AssetsTrapped", "Attempted", "FeesPaid", "InvalidQuerier", "InvalidQuerierVersion", "InvalidResponder", "InvalidResponderVersion", "Notified", "NotifyDecodeFailed", "NotifyDispatchError", "NotifyOverweight", "NotifyTargetMigrationFail", "NotifyTargetSendFail", "ProcessXcmError", "ResponseReady", "ResponseTaken", "SendFailed", "Sent", "SupportedVersionChanged", "UnexpectedResponse", "VersionChangeNotified", "VersionMigrationFinished", "VersionNotifyRequested", "VersionNotifyStarted", "VersionNotifyUnrequested"],
  "Preimage": ["Cleared", "Noted", "Requested"],
  "Proxy": ["Announced", "DepositPoked", "ProxyAdded", "ProxyExecuted", "ProxyRemoved", "PureCreated"],
  "Referenda": ["Approved", "Cancelled", "ConfirmAborted", "ConfirmStarted", "Confirmed", "DecisionDepositPlaced", "DecisionDepositRefunded", "DecisionStarted", "DepositSlashed", "Killed", "MetadataCleared", "MetadataSet", "Rejected", "SubmissionDepositRefunded", "Submitted", "TimedOut"],
  "Scheduler": ["AgendaIncomplete", "CallUnavailable", "Canceled", "Dispatched", "PeriodicFailed", "PermanentlyOverweight", "RetryCancelled", "RetryFailed", "RetrySet", "Scheduled"],
  "Session": ["NewSession", "ValidatorDisabled", "ValidatorReenabled"],
  "Sudo": ["KeyChanged", "KeyRemoved", "Sudid", "SudoAsDone"],
  "System": ["CodeUpdated", "ExtrinsicFailed", "ExtrinsicSuccess", "KilledAccount", "NewAccount", "RejectedInvalidAuthorizedUpgrade", "Remarked", "UpgradeAuthorized"],
  "TransactionPayment": ["TransactionFeePaid"],
  "Treasury": ["AssetSpendApproved", "AssetSpendVoided", "Awarded", "Burnt", "Deposit", "Paid", "PaymentFailed", "Rollover", "SpendApproved", "SpendProcessed", "Spending", "UpdatedInactive"],
  "Uniques": ["ApprovalCancelled", "ApprovedTransfer", "AttributeCleared", "AttributeSet", "Burned", "CollectionFrozen", "CollectionMaxSupplySet", "CollectionMetadataCleared", "CollectionMetadataSet", "CollectionThawed", "Created", "Destroyed", "ForceCreated", "Frozen", "Issued", "ItemBought", "ItemPriceRemoved", "ItemPriceSet", "ItemStatusChanged", "MetadataCleared", "MetadataSet", "OwnerChanged", "OwnershipAcceptanceChanged", "Redeposited", "TeamChanged", "Thawed", "Transferred"],
  "Utility": ["BatchCompleted", "BatchCompletedWithErrors", "BatchInterrupted", "DispatchedAs", "IfElseFallbackCalled", "IfElseMainSuccess", "ItemCompleted", "ItemFailed"],
  "Vesting": ["VestingCompleted", "VestingUpdated"],
  "XcmpQueue": ["XcmpMessageSent"]
}

// Storage metadata: maps pallet names to their storage locations (from base.yaml)
export const storageMetadata: PalletMetadata = {
  "Balances": ["TotalIssuance", "InactiveIssuance"],
  "System": ["Account"],
  "Acurast": ["StoredJobRegistration"],
  "AcurastCompute": ["Commitments", "ComputeCommitments", "Delegations", "Metrics", "MetricsEpochSum", "StakeBasedRewards"],
  "AcurastTokenClaim": ["Claimed", "Vesting"]
}

// Config rules from base.yaml storage_indexing
export const configRules = [
  'job_registration_stored',
  'job_registration_removed',
  'compute_committed',
  'stake_more',
  'stake_more_metrics',
  'compute_commitment_cooldown_started',
  'compute_commitment_ended',
  'slashed',
  'delegated',
  'delegated_more',
  'delegation_cooldown_started',
  'delegation_ended',
  'redelegated',
  'delegator_withdrew',
  'committer_withdrew',
  'delegator_compounded',
  'committer_compounded',
  'processor_heartbeat_metrics',
  'manager_metrics_epoch_sum',
  'stake_based_rewards_snapshot',
  'total_issuance',
  'token_claimed',
  'token_claimed_v2',
  'token_vested'
]
